export const LanguagesTTS = [
  {
    id: "105",
    flag: "./static/flags/South-Africa-Flag.png",
    language: "Afrikaans (South Africa)",
    code: "af-ZA",
  },
  {
    id: "106",
    flag: "./static/flags/Ethiopia-Flag.png",
    language: "Amharic (Ethiopia)",
    code: "am-ET",
  },
  {
    id: "107",
    flag: "./static/flags/Armenia-Flag.png",
    language: "Armenian (Armenia)",
    code: "hy-AM",
  },
  {
    id: "108",
    flag: "./static/flags/Azerbaijan-Flag.png",
    language: "Azerbaijani (Azerbaijan)",
    code: "az-AZ",
  },
  {
    id: "109",
    flag: "./static/flags/Indonezia-Flag.png",
    language: "Indonesian (Indonesia)",
    code: "id-ID",
  },
  {
    id: "110",
    flag: "./static/flags/Malaysia-Flag.png",
    language: "Malay (Malaysia)",
    code: "ms-MY",
  },
  {
    id: "111",
    flag: "./static/flags/Bangladesh-Flag.png",
    language: "Bengali (Bangladesh)",
    code: "bn-BD",
  },
  {
    id: "112",
    flag: "./static/flags/India-Flag.png",
    language: "Bengali (India)",
    code: "bn-IN",
  },
  {
    id: "113",
    flag: "./static/flags/Spain-Flag.png",
    language: "Catalan (Spain)",
    code: "ca-ES",
  },
  {
    id: "114",
    flag: "./static/flags/Czech-Republic-Flag.png",
    language: "Czech (Czech Republic)",
    code: "cs-CZ",
  },
  {
    id: "115",
    flag: "./static/flags/Denmark-Flag.png",
    language: "Danish (Denmark)",
    code: "da-DK",
  },
  {
    id: "116",
    flag: "./static/flags/Germany-Flag.png",
    language: "German (Germany)",
    code: "de-DE",
  },
  {
    id: "117",
    flag: "./static/flags/Australia-Flag.png",
    language: "English (Australia)",
    code: "en-AU",
  },
  {
    id: "118",
    flag: "./static/flags/Canada-Flag.png",
    language: "English (Canada)",
    code: "en-CA",
  },
  {
    id: "119",
    flag: "./static/flags/Ghana-Flag.png",
    language: "English (Ghana)",
    code: "en-GH",
  },
  {
    id: "120",
    flag: "./static/flags/United-Kingdom-Flag.png",
    language: "English (United Kingdom)",
    code: "en-GB",
  },
  {
    id: "121",
    flag: "./static/flags/India-Flag.png",
    language: "English (India)",
    code: "en-IN",
  },
  {
    id: "122",
    flag: "./static/flags/Ireland-Flag.png",
    language: "English (Ireland)",
    code: "en-IE",
  },
  {
    id: "123",
    flag: "./static/flags/Kenya-Flag.png",
    language: "English (Kenya)",
    code: "en-KE",
  },
  {
    id: "124",
    flag: "./static/flags/New-Zealand-Flag.png",
    language: "English (New Zealand)",
    code: "en-NZ",
  },
  {
    id: "125",
    flag: "./static/flags/Nigeria-Flag.png",
    language: "English (Nigeria)",
    code: "en-NG",
  },
  {
    id: "126",
    flag: "./static/flags/Philippines-Flag.png",
    language: "English (Philippines)",
    code: "en-PH",
  },
  {
    id: "127",
    flag: "./static/flags/Singapore-Flag.png",
    language: "English (Singapore)",
    code: "en-SG",
  },
  {
    id: "128",
    flag: "./static/flags/South-Africa-Flag.png",
    language: "English (South Africa)",
    code: "en-ZA",
  },
  {
    id: "129",
    flag: "./static/flags/Tanzania-Flag.png",
    language: "English (Tanzania)",
    code: "en-TZ",
  },
  {
    id: "130",
    flag: "./static/flags/United-States-of-America-Flag.png",
    language: "English (United States)",
    code: "en-US",
  },
  {
    id: "131",
    flag: "./static/flags/Argentina-Flag.png",
    language: "Spanish (Argentina)",
    code: "es-AR",
  },
  {
    id: "132",
    flag: "./static/flags/Bolivia-Flag.png",
    language: "Spanish (Bolivia)",
    code: "es-BO",
  },
  {
    id: "133",
    flag: "./static/flags/Chile-Flag.png",
    language: "Spanish (Chile)",
    code: "es-CL",
  },
  {
    id: "134",
    flag: "./static/flags/Colombia-Flag.png",
    language: "Spanish (Colombia)",
    code: "es-CO",
  },
  {
    id: "135",
    flag: "./static/flags/Costa-Rica-Flag.png",
    language: "Spanish (Costa Rica)",
    code: "es-CR",
  },
  {
    id: "136",
    flag: "./static/flags/Ecuador-Flag.png",
    language: "Spanish (Ecuador)",
    code: "es-EC",
  },
  {
    id: "137",
    flag: "./static/flags/El-Salvador-Flag.png",
    language: "Spanish (El Salvador)",
    code: "es-SV",
  },
  {
    id: "138",
    flag: "./static/flags/Spain-Flag.png",
    language: "Spanish (Spain)",
    code: "es-ES",
  },
  {
    id: "139",
    flag: "./static/flags/United-States-of-America-Flag.png",
    language: "Spanish (United States)",
    code: "es-US",
  },
  {
    id: "140",
    flag: "./static/flags/Guatemala-Flag.png",
    language: "Spanish (Guatemala)",
    code: "es-GT",
  },
  {
    id: "141",
    flag: "./static/flags/Honduras-Flag.png",
    language: "Spanish (Honduras)",
    code: "es-HN",
  },
  {
    id: "142",
    flag: "./static/flags/Mexico-Flag.png",
    language: "Spanish (Mexico)",
    code: "es-MX",
  },
  {
    id: "143",
    flag: "./static/flags/Nicaragua-Flag.png",
    language: "Spanish (Nicaragua)",
    code: "es-NI",
  },
  {
    id: "144",
    flag: "./static/flags/Panama-Flag.png",
    language: "Spanish (Panama)",
    code: "es-PA",
  },
  {
    id: "145",
    flag: "./static/flags/Paraguay-Flag.png",
    language: "Spanish (Paraguay)",
    code: "es-PY",
  },
  {
    id: "146",
    flag: "./static/flags/Peru-Flag.png",
    language: "Spanish (Peru)",
    code: "es-PE",
  },
  {
    id: "147",
    flag: "./static/flags/Puerto-Rico-Flag.png",
    language: "Spanish (Puerto Rico)",
    code: "es-PR",
  },
  {
    id: "148",
    flag: "./static/flags/Dominican-Republic-Flag.png",
    language: "Spanish (Dominican Republic)",
    code: "es-DO",
  },
  {
    id: "149",
    flag: "./static/flags/Uruguay-Flag.png",
    language: "Spanish (Uruguay)",
    code: "es-UY",
  },
  {
    id: "150",
    flag: "./static/flags/Venezuela-Flag.png",
    language: "Spanish (Venezuela)",
    code: "es-VE",
  },
  {
    id: "151",
    flag: "./static/flags/Spain-Flag.png",
    language: "Basque (Spain)",
    code: "eu-ES",
  },
  {
    id: "152",
    flag: "./static/flags/Philippines-Flag.png",
    language: "Filipino (Philippines)",
    code: "fil-PH",
  },
  {
    id: "153",
    flag: "./static/flags/Canada-Flag.png",
    language: "French (Canada)",
    code: "fr-CA",
  },
  {
    id: "154",
    flag: "./static/flags/France-Flag.png",
    language: "French (France)",
    code: "fr-FR",
  },
  {
    id: "155",
    flag: "./static/flags/Spain-Flag.png",
    language: "Galician (Spain)",
    code: "gl-ES",
  },
  {
    id: "156",
    flag: "./static/flags/Georgia-Flag.png",
    language: "Georgian (Georgia)",
    code: "ka-GE",
  },
  {
    id: "157",
    flag: "./static/flags/India-Flag.png",
    language: "Gujarati (India)",
    code: "gu-IN",
  },
  {
    id: "158",
    flag: "./static/flags/Croatia-Flag.png",
    language: "Croatian (Croatia)",
    code: "hr-HR",
  },
  {
    id: "159",
    flag: "./static/flags/South-Africa-Flag.png",
    language: "Zulu (South Africa)",
    code: "zu-ZA",
  },
  {
    id: "160",
    flag: "./static/flags/Iceland-Flag.png",
    language: "Icelandic (Iceland)",
    code: "is-IS",
  },
  {
    id: "161",
    flag: "./static/flags/Italy-Flag.png",
    language: "Italian (Italy)",
    code: "it-IT",
  },
  {
    id: "162",
    flag: "./static/flags/Indonezia-Flag.png",
    language: "Javanese (Indonesia)",
    code: "jv-ID",
  },
  {
    id: "163",
    flag: "./static/flags/India-Flag.png",
    language: "Kannada (India)",
    code: "kn-IN",
  },
  {
    id: "164",
    flag: "./static/flags/Cambodia-Flag.png",
    language: "Khmer (Cambodia)",
    code: "km-KH",
  },
  {
    id: "165",
    flag: "./static/flags/Laos-Flag.png",
    language: "Lao (Laos)",
    code: "lo-LA",
  },
  {
    id: "166",
    flag: "./static/flags/Latvia-Flag.png",
    language: "Latvian (Latvia)",
    code: "lv-LV",
  },
  {
    id: "167",
    flag: "./static/flags/Lithuania-Flag.png",
    language: "Lithuanian (Lithuania)",
    code: "lt-LT",
  },
  {
    id: "168",
    flag: "./static/flags/Hungary-Flag.png",
    language: "Hungarian (Hungary)",
    code: "hu-HU",
  },
  {
    id: "169",
    flag: "./static/flags/India-Flag.png",
    language: "Malayalam (India)",
    code: "ml-IN",
  },
  {
    id: "170",
    flag: "./static/flags/India-Flag.png",
    language: "Marathi (India)",
    code: "mr-IN",
  },
  {
    id: "171",
    flag: "./static/flags/Netherlands-Flag.png",
    language: "Dutch (Netherlands)",
    code: "nl-NL",
  },
  {
    id: "172",
    flag: "./static/flags/Nepal-Flag.png",
    language: "Nepali (Nepal)",
    code: "ne-NP",
  },
  {
    id: "173",
    flag: "./static/flags/Norway-Flag.png",
    language: "Norwegian Bokmål (Norway)",
    code: "nb-NO",
  },
  {
    id: "174",
    flag: "./static/flags/Poland-Flag.png",
    language: "Polish (Poland)",
    code: "pl-PL",
  },
  {
    id: "175",
    flag: "./static/flags/Brazil-Flag.png",
    language: "Portuguese (Brazil)",
    code: "pt-BR",
  },
  {
    id: "176",
    flag: "./static/flags/Portugal-Flag.png",
    language: "Portuguese (Portugal)",
    code: "pt-PT",
  },
  {
    id: "177",
    flag: "./static/flags/Romania-Flag.png",
    language: "Romanian (Romania)",
    code: "ro-RO",
  },
  {
    id: "178",
    flag: "./static/flags/Sri-Lanka-Flag.png",
    language: "Sinhala (Sri Lanka)",
    code: "si-LK",
  },
  {
    id: "179",
    flag: "./static/flags/Slovakia-Flag.png",
    language: "Slovak (Slovakia)",
    code: "sk-SK",
  },
  {
    id: "180",
    flag: "./static/flags/Slovenia-Flag.png",
    language: "Slovenian (Slovenia)",
    code: "sl-SI",
  },
  {
    id: "181",
    flag: "./static/flags/Indonezia-Flag.png",
    language: "Sundanese (Indonesia)",
    code: "su-ID",
  },
  {
    id: "182",
    flag: "./static/flags/Tanzania-Flag.png",
    language: "Swahili (Tanzania)",
    code: "sw-TZ",
  },
  {
    id: "183",
    flag: "./static/flags/Kenya-Flag.png",
    language: "Swahili (Kenya)",
    code: "sw-KE",
  },
  {
    id: "184",
    flag: "./static/flags/Finland-Flag.png",
    language: "Finnish (Finland)",
    code: "fi-FI",
  },
  {
    id: "185",
    flag: "./static/flags/Sweden-Flag.png",
    language: "Swedish (Sweden)",
    code: "sv-SE",
  },
  {
    id: "186",
    flag: "./static/flags/India-Flag.png",
    language: "Tamil (India)",
    code: "ta-IN",
  },
  {
    id: "187",
    flag: "./static/flags/Singapore-Flag.png",
    language: "Tamil (Singapore)",
    code: "ta-SG",
  },
  {
    id: "188",
    flag: "./static/flags/Sri-Lanka-Flag.png",
    language: "Tamil (Sri Lanka)",
    code: "ta-LK",
  },
  {
    id: "189",
    flag: "./static/flags/Malaysia-Flag.png",
    language: "Tamil (Malaysia)",
    code: "ta-MY",
  },
  {
    id: "190",
    flag: "./static/flags/India-Flag.png",
    language: "Telugu (India)",
    code: "te-IN",
  },
  {
    id: "191",
    flag: "./static/flags/Viet-Nam-Flag.png",
    language: "Vietnamese (Vietnam)",
    code: "vi-VN",
  },
  {
    id: "192",
    flag: "./static/flags/Turkey-Flag.png",
    language: "Turkish (Turkey)",
    code: "tr-TR",
  },
  {
    id: "193",
    flag: "./static/flags/Pakistan-Flag.png",
    language: "Urdu (Pakistan)",
    code: "ur-PK",
  },
  {
    id: "194",
    flag: "./static/flags/India-Flag.png",
    language: "Urdu (India)",
    code: "ur-IN",
  },
  {
    id: "195",
    flag: "./static/flags/Greece-Flag.png",
    language: "Greek (Greece)",
    code: "el-GR",
  },
  {
    id: "196",
    flag: "./static/flags/Bulgaria-Flag.png",
    language: "Bulgarian (Bulgaria)",
    code: "bg-BG",
  },
  {
    id: "197",
    flag: "./static/flags/Russian-Federation-Flag.png",
    language: "Russian (Russia)",
    code: "ru-RU",
  },
  {
    id: "198",
    flag: "./static/flags/Serbia-Flag.png",
    language: "Serbian (Serbia)",
    code: "sr-RS",
  },
  {
    id: "199",
    flag: "./static/flags/Ukraine-Flag.png",
    language: "Ukrainian (Ukraine)",
    code: "uk-UA",
  },
  {
    id: "200",
    flag: "./static/flags/Israel-Flag.png",
    language: "Hebrew (Israel)",
    code: "he-IL",
  },
  {
    id: "201",
    flag: "./static/flags/Israel-Flag.png",
    language: "Arabic (Israel)",
    code: "ar-IL",
  },
  {
    id: "202",
    flag: "./static/flags/Jordan-Flag.png",
    language: "Arabic (Jordan)",
    code: "ar-JO",
  },
  {
    id: "203",
    flag: "./static/flags/United-Arab-Emirates-Flag.png",
    language: "Arabic (United Arab Emirates)",
    code: "ar-AE",
  },
  {
    id: "204",
    flag: "./static/flags/Bahrain-Flag.png",
    language: "Arabic (Bahrain)",
    code: "ar-BH",
  },
  {
    id: "205",
    flag: "./static/flags/Algeria-Flag.png",
    language: "Arabic (Algeria)",
    code: "ar-DZ",
  },
  {
    id: "206",
    flag: "./static/flags/Saudi-Arabia-Flag.png",
    language: "Arabic (Saudi Arabia)",
    code: "ar-SA",
  },
  {
    id: "207",
    flag: "./static/flags/Iraq-Flag.png",
    language: "Arabic (Iraq)",
    code: "ar-IQ",
  },
  {
    id: "208",
    flag: "./static/flags/Kuwait-Flag.png",
    language: "Arabic (Kuwait)",
    code: "ar-KW",
  },
  {
    id: "209",
    flag: "./static/flags/Morocco-Flag.png",
    language: "Arabic (Morocco)",
    code: "ar-MA",
  },
  {
    id: "210",
    flag: "./static/flags/Tunisia-Flag.png",
    language: "Arabic (Tunisia)",
    code: "ar-TN",
  },
  {
    id: "211",
    flag: "./static/flags/Oman-Flag.png",
    language: "Arabic (Oman)",
    code: "ar-OM",
  },
  {
    id: "212",
    flag: "./static/flags/Palestine-Flag.png",
    language: "Arabic (State of Palestine)",
    code: "ar-PS",
  },
  {
    id: "213",
    flag: "./static/flags/Qatar-Flag.png",
    language: "Arabic (Qatar)",
    code: "ar-QA",
  },
  {
    id: "214",
    flag: "./static/flags/Lebanon-Flag.png",
    language: "Arabic (Lebanon)",
    code: "ar-LB",
  },
  {
    id: "215",
    flag: "./static/flags/Egypt-Flag.png",
    language: "Arabic (Egypt)",
    code: "ar-EG",
  },
  {
    id: "216",
    flag: "./static/flags/Iran-Flag.png",
    language: "Persian (Iran)",
    code: "fa-IR",
  },
  {
    id: "217",
    flag: "./static/flags/India-Flag.png",
    language: "Hindi (India)",
    code: "hi-IN",
  },
  {
    id: "218",
    flag: "./static/flags/Thailand-Flag.png",
    language: "Thai (Thailand)",
    code: "th-TH",
  },
  {
    id: "219",
    flag: "./static/flags/South-Korea-Flag.png",
    language: "Korean (South Korea)",
    code: "ko-KR",
  },
  {
    id: "220",
    flag: "./static/flags/Taiwan-Flag.png",
    language: "Chinese, Mandarin (Traditional, Taiwan)",
    code: "zh-TW",
  },
  {
    id: "221",
    flag: "./static/flags/Hong-Kong-Flag.png",
    language: "Chinese, Cantonese (Traditional, Hong Kong)",
    code: "yue-Hant-HK",
  },
  {
    id: "222",
    flag: "./static/flags/Japan-Flag.png",
    language: "Japanese (Japan)",
    code: "ja-JP",
  },
  {
    id: "223",
    flag: "./static/flags/Hong-Kong-Flag.png",
    language: "Chinese, Mandarin (Simplified, Hong Kong)",
    code: "zh-HK",
  },
  {
    id: "224",
    flag: "./static/flags/China-Flag.png",
    language: "Chinese, Mandarin (Simplified, China)",
    code: "zh",
  },
];
