export const LanguagesData = [
  {
    id: "1",
    flag: "./static/flags/Albania-Flag.png",
    language: "Afrikaans",
    code: "af",
  },
  {
    id: "2",
    flag: "./static/flags/Albania-Flag.png",
    language: "Albanian",
    code: "sq",
  },
  {
    id: "3",
    flag: "./static/flags/Albania-Flag.png",
    language: "Amharic",
    code: "am",
  },
  {
    id: "4",
    flag: "./static/flags/Albania-Flag.png",
    language: "Arabic",
    code: "ar",
  },
  {
    id: "5",
    flag: "./static/flags/Albania-Flag.png",
    language: "Armenian",
    code: "hy",
  },
  {
    id: "6",
    flag: "./static/flags/Albania-Flag.png",
    language: "Azerbaijani",
    code: "az",
  },
  {
    id: "7",
    flag: "./static/flags/Albania-Flag.png",
    language: "Basque",
    code: "eu",
  },
  {
    id: "8",
    flag: "./static/flags/Albania-Flag.png",
    language: "Belarusian",
    code: "be",
  },
  {
    id: "9",
    flag: "./static/flags/Albania-Flag.png",
    language: "Bengali",
    code: "bn",
  },
  {
    id: "10",
    flag: "./static/flags/Albania-Flag.png",
    language: "Bosnian",
    code: "bs",
  },
  {
    id: "11",
    flag: "./static/flags/Albania-Flag.png",
    language: "Bulgarian",
    code: "bg",
  },
  {
    id: "12",
    flag: "./static/flags/Albania-Flag.png",
    language: "Catalan",
    code: "ca",
  },
  {
    id: "13",
    flag: "./static/flags/Albania-Flag.png",
    language: "Cebuano",
    code: "ceb",
  },
  {
    id: "14",
    flag: "./static/flags/Albania-Flag.png",
    language: "Chinese (Simplified)",
    code: "zh-CN",
  },
  {
    id: "15",
    flag: "./static/flags/Albania-Flag.png",
    language: "Chinese (Traditional)",
    code: "zh-TW",
  },
  {
    id: "16",
    flag: "./static/flags/Albania-Flag.png",
    language: "Corsican",
    code: "co",
  },
  {
    id: "17",
    flag: "./static/flags/Albania-Flag.png",
    language: "Croatian",
    code: "hr",
  },
  {
    id: "18",
    flag: "./static/flags/Albania-Flag.png",
    language: "Czech",
    code: "cs",
  },
  {
    id: "19",
    flag: "./static/flags/Albania-Flag.png",
    language: "Danish",
    code: "da",
  },
  {
    id: "20",
    flag: "./static/flags/Albania-Flag.png",
    language: "Dutch",
    code: "nl",
  },
  {
    id: "21",
    flag: "./static/flags/Albania-Flag.png",
    language: "English",
    code: "en",
  },
  {
    id: "22",
    flag: "./static/flags/Albania-Flag.png",
    language: "Esperanto",
    code: "eo",
  },
  {
    id: "23",
    flag: "./static/flags/Albania-Flag.png",
    language: "Estonian",
    code: "et",
  },
  {
    id: "24",
    flag: "./static/flags/Albania-Flag.png",
    language: "Finnish",
    code: "fi",
  },
  {
    id: "25",
    flag: "./static/flags/Albania-Flag.png",
    language: "French",
    code: "fr",
  },
  {
    id: "26",
    flag: "./static/flags/Albania-Flag.png",
    language: "Frisian",
    code: "fy",
  },
  {
    id: "27",
    flag: "./static/flags/Albania-Flag.png",
    language: "Galician",
    code: "gl",
  },
  {
    id: "28",
    flag: "./static/flags/Albania-Flag.png",
    language: "Georgian",
    code: "ka",
  },
  {
    id: "29",
    flag: "./static/flags/Albania-Flag.png",
    language: "German",
    code: "de",
  },
  {
    id: "30",
    flag: "./static/flags/Albania-Flag.png",
    language: "Greek",
    code: "el",
  },
  {
    id: "31",
    flag: "./static/flags/Albania-Flag.png",
    language: "Gujarati",
    code: "gu",
  },
  {
    id: "32",
    flag: "./static/flags/Albania-Flag.png",
    language: "Haitian Creole",
    code: "ht",
  },
  {
    id: "33",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hausa",
    code: "ha",
  },
  {
    id: "34",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hawaiian",
    code: "haw",
  },
  {
    id: "35",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hebrew",
    code: "iw",
  },
  {
    id: "36",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hindi",
    code: "hi",
  },
  {
    id: "37",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hmong",
    code: "hmn",
  },
  {
    id: "38",
    flag: "./static/flags/Albania-Flag.png",
    language: "Hungarian",
    code: "hu",
  },
  {
    id: "39",
    flag: "./static/flags/Albania-Flag.png",
    language: "Icelandic",
    code: "is",
  },
  {
    id: "40",
    flag: "./static/flags/Albania-Flag.png",
    language: "Igbo",
    code: "ig",
  },
  {
    id: "41",
    flag: "./static/flags/Albania-Flag.png",
    language: "Indonesian",
    code: "id",
  },
  {
    id: "42",
    flag: "./static/flags/Albania-Flag.png",
    language: "Irish",
    code: "ga",
  },
  {
    id: "43",
    flag: "./static/flags/Albania-Flag.png",
    language: "Italian",
    code: "it",
  },
  {
    id: "44",
    flag: "./static/flags/Albania-Flag.png",
    language: "Japanese",
    code: "ja",
  },
  {
    id: "45",
    flag: "./static/flags/Albania-Flag.png",
    language: "Javanese",
    code: "jw",
  },
  {
    id: "46",
    flag: "./static/flags/Albania-Flag.png",
    language: "Kannada",
    code: "kn",
  },
  {
    id: "47",
    flag: "./static/flags/Albania-Flag.png",
    language: "Kazakh",
    code: "kk",
  },
  {
    id: "48",
    flag: "./static/flags/Albania-Flag.png",
    language: "Khmer",
    code: "km",
  },
  {
    id: "49",
    flag: "./static/flags/Albania-Flag.png",
    language: "Korean",
    code: "ko",
  },
  {
    id: "50",
    flag: "./static/flags/Albania-Flag.png",
    language: "Kurdish",
    code: "ku",
  },
  {
    id: "51",
    flag: "./static/flags/Albania-Flag.png",
    language: "Kyrgyz",
    code: "ky",
  },
  {
    id: "52",
    flag: "./static/flags/Albania-Flag.png",
    language: "Lao",
    code: "lo",
  },
  {
    id: "53",
    flag: "./static/flags/Albania-Flag.png",
    language: "Latin",
    code: "la",
  },
  {
    id: "54",
    flag: "./static/flags/Albania-Flag.png",
    language: "Latvian",
    code: "lv",
  },
  {
    id: "55",
    flag: "./static/flags/Albania-Flag.png",
    language: "Lithuanian",
    code: "lt",
  },
  {
    id: "56",
    flag: "./static/flags/Albania-Flag.png",
    language: "Luxembourgish",
    code: "lb",
  },
  {
    id: "57",
    flag: "./static/flags/Albania-Flag.png",
    language: "Macedonian",
    code: "mk",
  },
  {
    id: "58",
    flag: "./static/flags/Albania-Flag.png",
    language: "Malagasy",
    code: "mg",
  },
  {
    id: "59",
    flag: "./static/flags/Albania-Flag.png",
    language: "Malay",
    code: "ms",
  },
  {
    id: "60",
    flag: "./static/flags/Albania-Flag.png",
    language: "Malayalam",
    code: "ml",
  },
  {
    id: "61",
    flag: "./static/flags/Albania-Flag.png",
    language: "Maltese",
    code: "mt",
  },
  {
    id: "62",
    flag: "./static/flags/Albania-Flag.png",
    language: "Maori",
    code: "mi",
  },
  {
    id: "63",
    flag: "./static/flags/Albania-Flag.png",
    language: "Marathi",
    code: "mr",
  },
  {
    id: "64",
    flag: "./static/flags/Albania-Flag.png",
    language: "Mongolian",
    code: "mn",
  },
  {
    id: "65",
    flag: "./static/flags/Albania-Flag.png",
    language: "Myanmar (Burmese)",
    code: "my",
  },
  {
    id: "66",
    flag: "./static/flags/Albania-Flag.png",
    language: "Nepali",
    code: "ne",
  },
  {
    id: "67",
    flag: "./static/flags/Albania-Flag.png",
    language: "Norwegian",
    code: "no",
  },
  {
    id: "68",
    flag: "./static/flags/Albania-Flag.png",
    language: "Nyanja (Chichewa)",
    code: "ny",
  },
  {
    id: "69",
    flag: "./static/flags/Albania-Flag.png",
    language: "Pashto",
    code: "ps",
  },
  {
    id: "70",
    flag: "./static/flags/Albania-Flag.png",
    language: "Persian",
    code: "fa",
  },
  {
    id: "71",
    flag: "./static/flags/Albania-Flag.png",
    language: "Polish",
    code: "pl",
  },
  {
    id: "72",
    flag: "./static/flags/Albania-Flag.png",
    language: "Portuguese (Portugal, Brazil)",
    code: "pt",
  },
  {
    id: "73",
    flag: "./static/flags/Albania-Flag.png",
    language: "Punjabi",
    code: "pa",
  },
  {
    id: "74",
    flag: "./static/flags/Albania-Flag.png",
    language: "Romanian",
    code: "ro",
  },
  {
    id: "75",
    flag: "./static/flags/Albania-Flag.png",
    language: "Russian",
    code: "ru",
  },
  {
    id: "76",
    flag: "./static/flags/Albania-Flag.png",
    language: "Samoan",
    code: "sm",
  },
  {
    id: "77",
    flag: "./static/flags/Albania-Flag.png",
    language: "Scots Gaelic",
    code: "gd",
  },
  {
    id: "78",
    flag: "./static/flags/Albania-Flag.png",
    language: "Serbian",
    code: "sr",
  },
  {
    id: "79",
    flag: "./static/flags/Albania-Flag.png",
    language: "Sesotho",
    code: "st",
  },
  {
    id: "80",
    flag: "./static/flags/Albania-Flag.png",
    language: "Shona",
    code: "sn",
  },
  {
    id: "81",
    flag: "./static/flags/Albania-Flag.png",
    language: "Sindhi",
    code: "sd",
  },
  {
    id: "82",
    flag: "./static/flags/Albania-Flag.png",
    language: "Sinhala (Sinhalese)",
    code: "si",
  },
  {
    id: "83",
    flag: "./static/flags/Albania-Flag.png",
    language: "Slovak",
    code: "sk",
  },
  {
    id: "84",
    flag: "./static/flags/Albania-Flag.png",
    language: "Slovenian",
    code: "sl",
  },
  {
    id: "85",
    flag: "./static/flags/Albania-Flag.png",
    language: "Somali",
    code: "so",
  },
  {
    id: "86",
    flag: "./static/flags/Albania-Flag.png",
    language: "Spanish",
    code: "es",
  },
  {
    id: "87",
    flag: "./static/flags/Albania-Flag.png",
    language: "Sundanese",
    code: "su",
  },
  {
    id: "88",
    flag: "./static/flags/Albania-Flag.png",
    language: "Swahili",
    code: "sw",
  },
  {
    id: "89",
    flag: "./static/flags/Albania-Flag.png",
    language: "Swedish",
    code: "sv",
  },
  {
    id: "90",
    flag: "./static/flags/Albania-Flag.png",
    language: "Tagalog (Filipino)",
    code: "tl",
  },
  {
    id: "91",
    flag: "./static/flags/Albania-Flag.png",
    language: "Tajik",
    code: "tg",
  },
  {
    id: "92",
    flag: "./static/flags/Albania-Flag.png",
    language: "Tamil",
    code: "ta",
  },
  {
    id: "93",
    flag: "./static/flags/Albania-Flag.png",
    language: "Telugu",
    code: "te",
  },
  {
    id: "94",
    flag: "./static/flags/Albania-Flag.png",
    language: "Thai",
    code: "th",
  },
  {
    id: "95",
    flag: "./static/flags/Albania-Flag.png",
    language: "Turkish",
    code: "tr",
  },
  {
    id: "96",
    flag: "./static/flags/Albania-Flag.png",
    language: "Ukrainian",
    code: "uk",
  },
  {
    id: "97",
    flag: "./static/flags/Albania-Flag.png",
    language: "Urdu",
    code: "ur",
  },
  {
    id: "98",
    flag: "./static/flags/Albania-Flag.png",
    language: "Uzbek",
    code: "uz",
  },
  {
    id: "99",
    flag: "./static/flags/Albania-Flag.png",
    language: "Vietnamese",
    code: "vi",
  },
  {
    id: "100",
    flag: "./static/flags/Albania-Flag.png",
    language: "Welsh",
    code: "cy",
  },
  {
    id: "101",
    flag: "./static/flags/Albania-Flag.png",
    language: "Xhosa",
    code: "xh",
  },
  {
    id: "102",
    flag: "./static/flags/Albania-Flag.png",
    language: "Yiddish",
    code: "yi",
  },
  {
    id: "103",
    flag: "./static/flags/Albania-Flag.png",
    language: "Yoruba",
    code: "yo",
  },
  {
    id: "104",
    flag: "./static/flags/Albania-Flag.png",
    language: "Zulu",
    code: "zu",
  },
];
